# 对程序进行重新命名
spring:
  application:
    name: mytest
  #  表示文件编码强制使用 utf-8
  mandatory-file-encoding: utf-8
  #  设置 http 请求的编码
  http:
    encoding:
      enabled: true
      charset: UTF-8
  banner:
    location: banner.txt
    charset: UTF-8
  main:
    banner-mode: console
  redis:
    host: 192.168.204.5
    port: 6379
    database: 2
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:D:\sqlite\db\1596446563201crmPromo.db
    username: root
    password:
#    type: com.alibaba.druid.pool.DruidDataSource


#  profiles:
#    active: dev
#  config:
#    additional-location:
#  自定义配置 用Value注解进行获取
myConfig:
  myObject:
    myName: 张三${random.int}
    myAge: 29

server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: testhttp.demo.sqlitetest.model
  configuration:
    map-underscore-to-camel-case: true
